---
version: '2'

services:

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  # local DB

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: "trelolodb"
      POSTGRES_USER: "trelolo"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"

  # tunnel to localhost

  ngrok:
    container_name: ngrok
    image: wernight/ngrok
    ports:
      - "0.0.0.0:4040:4040"
    environment:
      # see possible environment variables here:
      # https://github.com/wernight/docker-ngrok
      NGROK_AUTH: <fill>
      NGROK_HOSTNAME: <fill>
      NGROK_PORT: "web:5000"
    links:
      - web

  web:
    container_name: web
    links:
      - postgres
    depends_on:
      - postgres

  worker:
    container_name: worker
    links:
      - postgres
    depends_on:
      - postgres
