"""empty message

Revision ID: 64d491f147e6
Revises: 
Create Date: 2017-02-13 10:31:22.943083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d491f147e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trello_id', sa.Unicode(length=45), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('hook_id', sa.Unicode(length=45), nullable=False),
    sa.Column('hook_url', sa.Unicode(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Unicode(length=45), nullable=False),
    sa.Column('board_id', sa.Unicode(length=45), nullable=False),
    sa.Column('parent_card_id', sa.Unicode(length=45), nullable=False),
    sa.Column('item_id', sa.Unicode(length=45), nullable=False),
    sa.Column('item_name', sa.Unicode(length=400), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('label', sa.Unicode(length=100), nullable=False),
    sa.Column('hook_id', sa.Unicode(length=45), nullable=False),
    sa.Column('hook_url', sa.Unicode(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_board_id'), 'cards', ['board_id'], unique=False)
    op.create_index(op.f('ix_cards_card_id'), 'cards', ['card_id'], unique=False)
    op.create_index(op.f('ix_cards_item_id'), 'cards', ['item_id'], unique=False)
    op.create_index(op.f('ix_cards_parent_card_id'), 'cards', ['parent_card_id'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=45), nullable=False),
    sa.Column('email', sa.Unicode(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Unicode(length=45), nullable=False),
    sa.Column('project_id', sa.Unicode(length=45), nullable=False),
    sa.Column('parent_card_id', sa.Unicode(length=45), nullable=False),
    sa.Column('item_id', sa.Unicode(length=45), nullable=False),
    sa.Column('item_name', sa.Unicode(length=400), nullable=False),
    sa.Column('label', sa.Unicode(length=100), nullable=False),
    sa.Column('milestone', sa.Unicode(length=100), nullable=False),
    sa.Column('hook_id', sa.Unicode(length=45), nullable=False),
    sa.Column('hook_url', sa.Unicode(length=400), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('target_type', sa.Unicode(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_issue_id'), 'issues', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issues_item_id'), 'issues', ['item_id'], unique=False)
    op.create_index(op.f('ix_issues_parent_card_id'), 'issues', ['parent_card_id'], unique=False)
    op.create_index(op.f('ix_issues_project_id'), 'issues', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_project_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_parent_card_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_item_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_issue_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_table('emails')
    op.drop_index(op.f('ix_cards_parent_card_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_item_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_board_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_table('boards')
    # ### end Alembic commands ###
